### ISSUE TITLE
Python errors during GIMP 2.10.30 (appimage) startup on Kubuntu 22.04

### ISSUE THREAD

**Issue by CaraesNaur** [kamilburda/gimp-export-layers#102]
I've just upgraded my workstation from Kubuntu 18.04 to Kubuntu 22.04.  I installed a lot of python2 packages expressly for GIMP, but it seems that was in vain.  I am now testing an AppImage of GIMP 2.10.30.

Upon starting the appimage the first time, I got a bunch of error messages regarding export_layers (3.3.1 from the previous OS).  I saw that there was an newer version so I dropped that into the plugins folder.

I saw on the install page about resetting the plugin's settings.  Since it doesn't appear in the File menu in this fresh install, I can't use that process.  I don't know Python well enough to attempt a manual reset of the settings.

#### What went wrong?

Upon GIMP AppImage startup with export_layers 3.3.5, the following errors are displayed:

    Traceback (most recent call last):
      File "/home/dracos/.config/GIMP/2.10/plug-ins/export_layers.py", line 21, in <module>
        from export_layers import pygimplib as pg
      File "/home/dracos/.config/GIMP/2.10/plug-ins/export_layers/pygimplib/__init__.py", line 56, in <module>
        from future.builtins import (
      File "/home/dracos/.config/GIMP/2.10/plug-ins/export_layers/pygimplib/_lib/future/future/builtins/__init__.py", line 10, in <module>
        from future.builtins.iterators import (filter, map, zip)
      File "/home/dracos/.config/GIMP/2.10/plug-ins/export_layers/pygimplib/_lib/future/future/builtins/iterators.py", line 43, in <module>
        from future.types import newrange as range
      File "/home/dracos/.config/GIMP/2.10/plug-ins/export_layers/pygimplib/_lib/future/future/types/__init__.py", line 243, in <module>
        from .newrange import newrange
      File "/home/dracos/.config/GIMP/2.10/plug-ins/export_layers/pygimplib/_lib/future/future/types/newrange.py", line 25, in <module>
        from future.backports.misc import count   # with step parameter on Py2.6
      File "/home/dracos/.config/GIMP/2.10/plug-ins/export_layers/pygimplib/_lib/future/future/backports/__init__.py", line 17, in <module>
        from .misc import (ceil,
      File "/home/dracos/.config/GIMP/2.10/plug-ins/export_layers/pygimplib/_lib/future/future/backports/misc.py", line 26, in <module>
        from socket import getaddrinfo, SOCK_STREAM, error, socket
      File "/usr/lib/python2.7/socket.py", line 68, in <module>
        from _ssl import \
    ImportError: cannot import name RAND_egd

The errors from 3.3.1 also traced back to RAND_egd:

    Traceback (most recent call last):
      File "/home/dracos/.config/GIMP/2.10/plug-ins/export_layers.py", line 38, in <module>
        from export_layers import pygimplib
      File "/home/dracos/.config/GIMP/2.10/plug-ins/export_layers/pygimplib/__init__.py", line 70, in <module>
        from future.builtins import *
      File "/home/dracos/.config/GIMP/2.10/plug-ins/export_layers/pygimplib/lib/future/future/builtins/__init__.py", line 10, in <module>
        from future.builtins.iterators import (filter, map, zip)
      File "/home/dracos/.config/GIMP/2.10/plug-ins/export_layers/pygimplib/lib/future/future/builtins/iterators.py", line 43, in <module>
        from future.types import newrange as range
      File "/home/dracos/.config/GIMP/2.10/plug-ins/export_layers/pygimplib/lib/future/future/types/__init__.py", line 243, in <module>
        from .newrange import newrange
      File "/home/dracos/.config/GIMP/2.10/plug-ins/export_layers/pygimplib/lib/future/future/types/newrange.py", line 25, in <module>
        from future.backports.misc import count   # with step parameter on Py2.6
      File "/home/dracos/.config/GIMP/2.10/plug-ins/export_layers/pygimplib/lib/future/future/backports/__init__.py", line 17, in <module>
        from .misc import (ceil,
      File "/home/dracos/.config/GIMP/2.10/plug-ins/export_layers/pygimplib/lib/future/future/backports/misc.py", line 26, in <module>
        from socket import getaddrinfo, SOCK_STREAM, error, socket
      File "/usr/lib/python2.7/socket.py", line 68, in <module>
        from _ssl import \
    ImportError: cannot import name RAND_egd

#### If you can, tell us the steps to reproduce the problem.

Run AppImage of GIMP 2.10.30, errors are shown during initial plugin scan.

#### Configuration

Version of Export Layers: 3.3.5

Version of GIMP: 2.10.30 (AppImage)

Operating system: Kubuntu 22.04

System installed python2 version: 2.7.18

Output from Python-Fu console: 

    GIMP 2.10.30 Python Console
    Python 2.7.18rc1 (default, Apr  7 2020, 12:05:55) 
    [GCC 9.3.0]

**Comment by kamilburda** [comment]
This might be an issue specific to the Python installation for Kubuntu 22.04.

You could try the following workaround:
1. Go to `/home/<your username>/.config/GIMP/2.10/plug-ins/export_layers/pygimplib/lib/future/future/backports`.
2. Back up the `misc.py` file just in case.
3. Unzip [this archive](https://github.com/kamilburda/gimp-export-layers/files/11142829/misc.zip) and replace the original `misc.py` with the one from the archive.

(Technical note: I removed a few lines of code from the `misc.py` file that imported SSL-related code which may cause the error. The code removed was responsible for backporting a bunch Python 3 features back to Python 2.7, which Export Layers does not make use of, so there's no harm in removing it.)

**Comment by kamilburda** [comment]
Alternatively, you could open `/usr/lib/python2.7/socket.py` and replace
```
    try:
        from _ssl import RAND_egd
    except ImportError:
        # LibreSSL does not provide RAND_egd
        pass
```

with

```
    # try:
        # from _ssl import RAND_egd
    # except ImportError:
        # # LibreSSL does not provide RAND_egd
        # pass
```

This should probably fix the issue properly.

**Comment by CaraesNaur** [comment]
Replacing `misc.py` in the plugin seems to have worked.  No errors at startup, the menu items are present, export works.

**Comment by kamilburda** [comment]
Thanks for the heads-up, great to hear it works!
