### ISSUE TITLE
Gimp 2.8.22 Crash: Unexpected Error Exporting Layers

### ISSUE THREAD

**Issue by Alzter** [kamilburda/gimp-export-layers#104]
#### What went wrong?
Whilst trying to export layers, export layers crashed.

``Export Layers encountered an unexpected error and has to close.``

``Traceback (most recent call last):
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\export_layers\gui\main.py", line 173, in func_wrapper
    func(self, *args, **kwargs)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\export_layers\gui\main.py", line 808, in _on_button_export_clicked
    self._exporter.export()
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\export_layers\exportlayers.py", line 243, in export
    self._process_items()
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\export_layers\exportlayers.py", line 579, in _process_items
    self._process_item(item)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\export_layers\exportlayers.py", line 593, in _process_item
    raw_item_copy = self._process_item_with_actions(item, self._image_copy, raw_item)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\export_layers\exportlayers.py", line 662, in _process_item_with_actions
    raw_item_copy = builtin_procedures.copy_and_insert_layer(image, raw_item, None, 0)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\export_layers\builtin_procedures.py", line 36, in copy_and_insert_layer
    layer, image, parent, position, remove_lock_attributes)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\export_layers\pygimplib\pdbutils.py", line 200, in copy_and_paste_layer
    pdb.gimp_item_set_lock_position(layer_copy, False)
error: procedure not found
``

#### If you can, tell us the steps to reproduce the problem.

I tried to export layers for a GIMP file.

#### Configuration

Version of Export Layers: I can't find any version information on the Export Layers dialog, so I'm not sure.

Version of GIMP: 2.8.22

Operating system: Windows 10 Home

Procedures and constraints added in Export Layers (in the Export Layers dialog, choose Settings → Show More Settings to display them): None

![image](https://github.com/kamilburda/gimp-export-layers/assets/22513909/972f806f-8f15-4f05-9ecb-076b8515f11e)

**Comment by Alzter** [comment]
Please also note that this error appears whenever I bring up the export layers dialog.

![image](https://github.com/kamilburda/gimp-export-layers/assets/22513909/126367e5-1edc-4890-9013-72dddf84be13)

**Comment by kamilburda** [comment]
Thanks for the report. I made [a new release](https://github.com/kamilburda/gimp-export-layers/releases/tag/3.3.7) which fixes this bug.

The problem was that I was using GIMP features that were introduced in GIMP 2.10, causing backwards incompatibility with 2.8.
