### ISSUE TITLE
Error exporting layers

### ISSUE THREAD

**Issue by EarthsDefect** [kamilburda/gimp-export-layers#107]
Traceback (most recent call last):
  File "C:\Users\Jesse\Downloads\export_layers-4.0.1/export_layers/gui/main.py", line 1014, in _on_button_run_clicked
    self._batcher.run(**utils_.get_settings_for_batcher(self._settings['main']))
  File "C:\Users\Jesse\Downloads\export_layers-4.0.1/export_layers/batcher.py", line 361, in run
    self._process_items()
  File "C:\Users\Jesse\Downloads\export_layers-4.0.1/export_layers/batcher.py", line 872, in _process_items
    self._process_item(item)
  File "C:\Users\Jesse\Downloads\export_layers-4.0.1/export_layers/batcher.py", line 893, in _process_item
    self._process_item_with_actions(item, self._current_raw_item)
  File "C:\Users\Jesse\Downloads\export_layers-4.0.1/export_layers/batcher.py", line 947, in _process_item_with_actions
    additional_args_position=_BATCHER_ARG_POSITION_IN_ACTIONS)
  File "C:\Users\Jesse\Downloads\export_layers-4.0.1/export_layers/pygimplib/invoker.py", line 301, in invoke
    _invoke_action_with_foreach_actions(item, group)
  File "C:\Users\Jesse\Downloads\export_layers-4.0.1/export_layers/pygimplib/invoker.py", line 261, in _invoke_action_with_foreach_actions
    result_from_action = _invoke_action(item, group)
  File "C:\Users\Jesse\Downloads\export_layers-4.0.1/export_layers/pygimplib/invoker.py", line 233, in _invoke_action
    return next(item.generators_per_group[group])
  File "C:\Users\Jesse\Downloads\export_layers-4.0.1\export_layers\pygimplib\_lib\future/future/builtins/newnext.py", line 59, in newnext
    return iterator.next()
  File "C:\Users\Jesse\Downloads\export_layers-4.0.1/export_layers/export.py", line 131, in export
    output_directory, default_file_extension, file_extension_properties)
  File "C:\Users\Jesse\Downloads\export_layers-4.0.1/export_layers/export.py", line 279, in _export_item
    file_extension_properties)
  File "C:\Users\Jesse\Downloads\export_layers-4.0.1/export_layers/export.py", line 344, in _export_item_once_wrapper
    default_file_extension, file_extension_properties)
  File "C:\Users\Jesse\Downloads\export_layers-4.0.1/export_layers/export.py", line 384, in _export_item_once
    raise exceptions.ExportError(str(e), raw_item.name, default_file_extension)
ExportError: b'execution error
Layer: Frame 7
File extension: png'

**Comment by kamilburda** [comment]
Hi, thanks for the report. Can you provide more details? In particular:

* Version of GIMP
* Procedures and constraints used (in the Export Layers dialog, choose `Settings → Show More Settings` to display them)
* Is there any other error/warning message displayed in GIMP, such as a popup or a message in the bottom panel in GIMP?
* Does the error always occur for one particular layer only?
* Does the error always occur for the PNG format only?

**Comment by Kestrelguy** [comment]
I'm getting this same issue.
- GIMP version 2.10.38
- use layer size, layers, visible; file name `[layer name]_sans`
- no other warnings anywhere that I can see
- appears to always pick the first layer
- I was trying to convert to TGA
I thought it might possibly be that I was using backticks in the layer names, but removing those didn't change anything. Ditto for my layers all being text layers.

**Comment by kamilburda** [comment]
@Kestrelguy If it's OK with you, can you send me the XCF file containing the layers that cause the export to fail?

Also, in the meantime, does this happen if you export the entire image via `Export As...`?

**Comment by Kestrelguy** [comment]
[font_sans_serif.zip](https://github.com/user-attachments/files/16571309/font_sans_serif.zip)
here's the file.
bizarrely, when I try to export it, GIMP gives me an error about not recognizing the file type… but that wasn't happening the day I got the error in this thread. (in fact, I tried to use this specifically because I'd started exporting layers individually and then decided it was too tedious.)

**Comment by kamilburda** [comment]
Thanks for the file. I tried exporting the layers to PNG and TGA and it worked on my end (Windows 11, GIMP 2.10.38, Export Layers 4.1).

When you hit Export, do you see the dialog for adjusting TGA format options? If you see the error message instead, this may very well be a problem within Export Layers.

However, if the error message says "execution error", I have difficulties identifying the problem. The thing is, the error messages are spawned by GIMP or the file format plug-ins (not Export Layers) and I am relying on the description to help identify the problem.

In case you get the "unknown file type" message, I can think of two causes:
* In `Export As...`, you need to type the file extension explicitly in the `Name` field.
* If you have anti-malware software installed, it may have flagged some file format plug-ins as malware (which I find highly unlikely, though). If you go to Help -> Procedure Browser and type `file-png-save` in the Search field, it should yield a result. Ditto with `file-tga-save`. If not, then you may have to reinstall GIMP or try to restore the file(s) that your anti-malware quarantined.

**Comment by Kestrelguy** [comment]
okay, so as it turns out, my problem last night was that I'd removed the path to the plugins that managed all the file types. whoops.
having fixed that problem… the layer export plugin works fine??
I have no clue what happened, because when I tried a couple weeks ago, I got the giant block of code (multiple times in a row) in the original post, but I didn't get it at all last night or tonight. so that seems to have gone away on its own?
sorry for wasting your time.

**Comment by kamilburda** [comment]
No problem! Glad you got it working. ☺️

Export Layers depends on the file format plug-ins, so if those work properly, then the export should work fine.

**Comment by kamilburda** [comment]
Closing this as the original issue got stale.
